---
# tasks file for common

  - name: fetch docker apt key
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

  - name: Add docker repository
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

  - name: Refresh cache
    apt:
    update_cache: yes

  - name: Update distro
    apt:
    name: "*"
    state: latest

  - name: Update all packages to the latest version
    apt:
    upgrade: dist    

  - name: install packets (2)
    apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

  - name: install docker compose    
    get_url:
    url: https://github.com/docker/compose/releases/download/1.27.3/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755

  - name: copy Docker Compose files
    copy:
      src: task1/docker/{{ item }}
      dest: task1/docker/{{ item }}
    loop:
    - docker-compose.yml

  # using files parameter to use multiple docker-compose.yml files
  - name: deploy Docker Compose stack
    community.docker.docker_compose:
      project_src: task1/docker
      files:
      - docker-compose.yml

