version: '3.5'
services:
  dot_net_image:
    image: dot_net_image:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=new_db;username=super_admin;password=1qaz2wsx3edc"

  postgres_image:
    container_name: postgres_demo
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: 1qaz2wsx3edc
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres-db:
    driver: local
